cameraRemote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('remote.urls')),
]
if settings.DEBUG is True:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

remote/urls.py
from django.urls import path
from . import views

app_name = 'remote'

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('nytt_album', views.NewAlbum.as_view(), name="new_album"),
    path('<album>/ta_bilde', views.Capture.as_view(), name="capture"),
    path('<album>', views.AlbumView.as_view(), name="album"),
    path('<album>/<int:number>', views.PhotoView.as_view(), name="photo"),
    path('<album>/opptatt', views.Occupied.as_view(), name="occupied"),
    path('<album>/ikke_tilkoplet', views.NotConnected.as_view(), name="not_connected"),
]

remote/models.py
from django.db import models
from django.core.files.base import ContentFile
from django.core.exceptions import ValidationError
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from PIL import Image
import os
from io import BytesIO

THUMBNAIL_SIZE = 1024, 1024


class CameraStatus (models.Model):
    occupied = models.BooleanField(default=False)

    # make sure only one cameraStatus can exist
    def save(self, *args, **kwargs):
        if CameraStatus.objects.exists() and not self.pk:
            # self.pk == false -> the object is not yet stored in the database
            raise ValidationError("There can only be one CameraStatus instance")
        return super(CameraStatus, self).save(*args, **kwargs)


def create_folder(folder_location):
    try:
        os.makedirs(folder_location)
    except:
        print(folder_location + " already in place")


class Photo (models.Model):
    shot_time = models.DateTimeField(default=timezone.now)
    image = models.ImageField()
    image_lowres = models.ImageField()
    album = models.ForeignKey("Album", on_delete=models.CASCADE)
    number_in_album = models.IntegerField(default=0)  # for lookups

    def save(self, *args, **kwargs):
        self.album.last_modified = timezone.now()
        self.album.save()
        if not self.make_thumbnail():
            # set to a default thumbnail
            raise Exception('Could not create thumbnail - is the file type valid?')
        if not self.pk:
            self.number_in_album = Photo.objects.filter(album=self.album).count() + 1
        super(Photo, self).save(*args, **kwargs)

    def time_elapsed_since_taken(self):
        """ returns a string containing the time elapsed since the photo was taken """
        now = timezone.now()
        delta = now - self.shot_time
        if delta.days // 365 > 0:
            return "Mer enn " + str(delta.days // 365) + " år siden"

        if delta.days // 30 > 0:
            if delta.days // 30 == 1:
                return "Mer enn 1 måned siden"
            else:
                return "Mer enn " + str(delta.days // 30) + " måneder siden"

        if delta.days > 0:
            if delta.days == 1:
                return "1 dag siden"
            else:
                return str(delta.days) + " dager siden"

        hours = delta.seconds // 3600
        if hours == 1:
            hour_string = "1 time"
        else:
            hour_string = str(hours) + " timer"

        minutes = (delta.seconds % 3600) // 60
        if minutes == 1:
            minute_string = "1 minutt"
        else:
            minute_string = str(minutes) + " minutter"

        seconds = (delta.seconds % 3600) - minutes * 60
        if seconds == 1:
            second_string = "1 sekund"
        else:
            second_string = str(seconds) + " sekunder"

        if hours > 0:
            if minutes == 0:
                return hour_string + " siden"
            return hour_string + " og " + minute_string + " siden"
        if minutes > 0:
            return minute_string + " siden"
        else:
            return second_string + " siden"

    def make_thumbnail(self):
        image = Image.open(self.image.path)
        image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

        image_filename = self.image.url.split("/")[-1]
        image_folder = "/".join(self.image.path.split("/")[0:-1])
        create_folder(image_folder + "/lowres")
        rel_image_folder = "/".join(self.image.url.split("/")[2:-1])  # we have to omit media, therefore the [2:-1]

        thumb_filename = rel_image_folder + "/lowres/" + image_filename.split(".")[0] + "_lowres.JPG"

        # Save thumbnail to in-memory file as StringIO
        temp_thumb = BytesIO()
        image.save(temp_thumb, "JPEG")
        temp_thumb.seek(0)

        # set save=False, otherwise it will run in an infinite loop
        print("lowres_filename: " + thumb_filename)
        self.image_lowres.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        return True

    def get_absolute_url(self):
        return reverse("remote:photo", args=[self.album.slug, self.number_in_album])


class Album (models.Model):
    time_made = models.DateTimeField(default=timezone.now)
    last_modified = models.DateTimeField(default=timezone.now)
    priority = models.PositiveIntegerField(default=1)
    name = models.CharField("Navn", max_length=30)
    description = models.TextField("Beskrivelse", default="")
    slug = models.SlugField(max_length=30, allow_unicode=False, unique=True)
    hidden = models.BooleanField(default=False)

    class Meta:
        ordering = ['-priority', '-last_modified']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.description == "":
            self.description = "Dette albumet har ingen beskrivelse"
        super(Album, self).save(*args, **kwargs)

    def __str__(self):
        return "Album: " + self.name

    def get_absolute_url(self):
        return reverse("remote:album", args=[self.slug])

    def get_last_image_link(self):
        """ gets the path to the last image created in this albums folder """
        save_location = os.path.join(settings.BASE_DIR, "media", self.slug)
        try:
            f = open(os.path.join(save_location, ".image_number.txt"), "r")
        except IOError:
            return "No_image"
        image_count = int(f.readlines()[0])
        if image_count == 0:
            return "No_image"
        f.close()
        return self.slug + "/bilde_" + str(image_count) + ".JPG"


class Settings (models.Model):
    """
    A model for storing settings, making it possible to change settings on
    the django admin-site
    """
    show_full_size_image_on_capture = models.BooleanField(default=True)
    do_countdown = models.BooleanField(default=False)
    contact_first_name = models.CharField(max_length=12, default="noen")
    contact_phone_number = models.CharField(max_length=15, default="")
    main_album = models.ForeignKey(Album, blank=True, null=True, default=None, on_delete=models.SET_NULL)  # if you want only one album to be displayed, choose this

    def get_or_create_settings():
        if not Settings.objects.exists():
            return Settings.objects.create()
        return Settings.objects.all()[0]

    # Make sure only one settings instance can exist
    def save(self, *args, **kwargs):
        if Settings.objects.exists() and not self.pk:
            # self.pk == false -> the object is not yet stored in the database
            raise ValidationError("There can only be one Settings instance")
        return super(Settings, self).save(*args, **kwargs)

remote/forms.py
from django import forms
from .models import Album


class AlbumAddForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            "class": "form-control",
            "placeholder": "Navn på album",
            }
        ))
    description = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Albumbeskrivelse",
            }
        ))

    class Meta:
        model = Album
        fields = ["name", "description"]

remote/views.py
from django.shortcuts import redirect, get_object_or_404
from django.http import Http404
from django.urls import reverse
from django.views.generic import TemplateView, ListView, CreateView
from .models import CameraStatus, Album, Photo, Settings
from .forms import AlbumAddForm
import os
import subprocess

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALBUM_PAGINATION = 18

def get_album_or_404(album_slug):
    project_settings = Settings.get_or_create_settings()
    if project_settings.main_album is not None and project_settings.main_album.slug != album_slug:
        raise Http404
    album = get_object_or_404(Album, slug=album_slug)
    if album.hidden:
        raise Http404
    return album


class Index(ListView):
    template_name = "remote/index.html"
    context_object_name = "albums"

    def get(self, request, *args, **kwargs):
        """ redirects to main album if main album is set """
        project_settings = Settings.get_or_create_settings()
        if project_settings.main_album is not None:
            return redirect(reverse("remote:album", args=[project_settings.main_album.slug]))
        return super(Index, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return Album.objects.filter(hidden=False)


class NewAlbum(CreateView):
    template_name = "remote/new_album.html"
    model = Album
    form_class = AlbumAddForm


def get_or_create_camera_status():
    if not CameraStatus.objects.exists():
        return CameraStatus.objects.create()
    return CameraStatus.objects.all()[0]


class Capture(TemplateView):
    template_name = "remote/capture.html"

    def get_context_data(self, **kwargs):
        context = super(Capture, self).get_context_data(**kwargs)
        photo = Photo.objects.all().last()
        if (Settings.get_or_create_settings().show_full_size_image_on_capture):
            context["image_link"] = photo.image.url
        else:
            context["image_link"] = photo.image_lowres.url
        context["album"] = get_album_or_404(self.kwargs["album"])
        return context

    def get(self, request, *args, **kwargs):
        album = get_album_or_404(self.kwargs["album"])

        status = get_or_create_camera_status()
        if (status.occupied):
            return redirect(reverse("remote:occupied", args=[album.slug]))
        status.occupied = True
        status.save()
        last_image_link = album.get_last_image_link()
        if (Settings.get_or_create_settings().do_countdown):
            subprocess.call(["python3", "remote/image_capture.py", album.slug, "T"])
        else:
            subprocess.call(["python3", "remote/image_capture.py", album.slug])
        status.occupied = False
        status.save()
        next_image_link = album.get_last_image_link()
        if next_image_link == last_image_link:  # this means no image was added
            return redirect(reverse("remote:not_connected", args=[album.slug]))
        photo = Photo()
        photo.album = album
        photo.image.name = next_image_link
        photo.save()
        return super(Capture, self).get(request, *args, **kwargs)


class AlbumView(ListView):
    template_name = "remote/album.html"
    context_object_name = "photos"
    model = Album
    paginate_by = ALBUM_PAGINATION

    def get_context_data(self, **kwargs):
        context = super(AlbumView, self).get_context_data(**kwargs)
        context["album"] = get_album_or_404(self.kwargs["album"])
        project_settings = Settings.get_or_create_settings()
        context["show_index_link"] = True
        if project_settings.main_album is not None:
            context["show_index_link"] = False
        return context

    def get_queryset(self):
        album = get_album_or_404(self.kwargs["album"])
        return Photo.objects.filter(album=album).order_by('-shot_time')


class PhotoView(TemplateView):
    template_name = "remote/photo.html"
    context_object_name = "photo"

    def get_context_data(self, **kwargs):
        album = get_album_or_404(self.kwargs["album"])
        photo = get_object_or_404(Photo, album=album, number_in_album=self.kwargs["number"])
        context = super(PhotoView, self).get_context_data(**kwargs)
        context["photo"] = photo
        context["album"] = album
        photos_in_album = Photo.objects.filter(album=album).count()
        number_in_album = self.kwargs["number"]
        context["photos_in_album"] = photos_in_album
        context["current_photo"] = photos_in_album - number_in_album + 1
        if number_in_album < photos_in_album:
            context["previous_image_link"] = reverse("remote:photo", args=[album.slug, number_in_album + 1])
        if number_in_album > 1:
            context["next_image_link"] = reverse("remote:photo", args=[album.slug, number_in_album - 1])
        back_to_album_link = reverse("remote:album", args=[album.slug])
        page_in_album = ((photos_in_album - number_in_album) // ALBUM_PAGINATION) + 1
        if page_in_album > 1:
            back_to_album_link += ("?page=" + str(page_in_album))
        context["back_to_album_link"] = back_to_album_link
        return context


class Occupied(TemplateView):
    template_name = "remote/occupied.html"

    def get_context_data(self, **kwargs):
        album = get_album_or_404(self.kwargs["album"])
        context = super(Occupied, self).get_context_data(**kwargs)
        context["album"] = album
        return context


class NotConnected(TemplateView):
    template_name = "remote/not_connected.html"

    def get_context_data(self, **kwargs):
        album = get_album_or_404(self.kwargs["album"])
        context = super(NotConnected, self).get_context_data(**kwargs)
        context["album"] = album
        return context

remote/templates/remote/album.html
{% extends "remote/base.html" %}
{% block content %}
    <main role="main">
	<section class="jumbotron text-center">
	    <div class="container">
		<h1 class="jumbotron-heading">{{ album.name }}</h1>
		<p class="lead text-muted">{{ album.description }}</p>
		<p>
		    <a href="{% url 'remote:capture' album.slug %}" class="btn btn-primary my-2">Ta nytt bilde til album</a>
		    {% if show_index_link %}
			<a href="{% url 'remote:index' %}" class="btn btn-secondary my-2">Tilbake til albumliste</a>
		    {% endif %}
		</p>
	    </div>
	</section>

	<div class="album py-4 bg-light">
	    <div class="container">
		{% if is_paginated %}
		    <div class="album-pagination-top">
			{% include "remote/album_pagination.html" %}
		    </div>
		{% endif %}
		{% if photos %}
		    <div class="row">
			{% for photo in photos %}
			    <div class="col-md-4">
				<div class="card mb-4 shadow-sm">
				    <a href="{{ photo.get_absolute_url }}">
					<img class="card-img-top" src="{{ photo.image_lowres.url }}" alt="Card image cap">
				    </a>
				    <div class="card-body">
					<!-- <p class="card-text">Her går det senere an å legge inn en beskrivelse av bildet??</p> -->
					<div class="d-flex justify-content-between align-items-center">
					    <a href="{{ photo.get_absolute_url }}">
						<button type="button" class="btn btn-sm btn-outline-secondary">Full størrelse</button>
					    </a>
					    <small class="text-muted">{{ photo.time_elapsed_since_taken }}</small>
					</div>
				    </div>
				</div>
			    </div>

			{% endfor %}
		    </div>
		{% else %}
		    <div class="text-center">
			<p class="jumbotron-heading">Det er ingen bilder i albumet ennå :(</p>
		    </div>
		{% endif %}
		{% if is_paginated %}
		    <div class="album-pagination-bottom">
			{% include "remote/album_pagination.html" %}
		    </div>
		{% endif %}
	    </div>
	</div>
    </main>
{% endblock content %}
{% block tips %}
    <p>Tips: Du kan også trykke på et bilde for å få det opp i full oppløsning, ideelt for lagring.</p>
{% endblock tips %}

remote/templates/remote/album_pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
	<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Forrige</a></li>
    {% else %}
	<li class="page-item disabled">
	    <a class="page-link" href="#" tabindex="-1">Forrige</a>
	</li>
    {% endif %}

    {% for i in paginator.page_range %}
	{% if i == page_obj.number %}
	    <li class="page-item active">
		<a class="page-link" href="?page={{ i }}">{{ i }} <span class="sr-only">(current)</span></a>
	    </li>
	{% else %}
	    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
	{% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
	<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Neste</a></li>
    {% else %}
	<li class="page-item disabled">
	    <a class="page-link" href="#" tabindex="-1">Neste</a>
	</li>
    {% endif %}
</ul>

remote/templates/remote/base.html
{% load static %}
<!doctype html>
<html lang="no">
    <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="{% static 'remote/favicon.ico' %}">

	<title>Fotobox</title>

	<!-- Bootstrap core CSS -->
	<link href="{% static 'remote/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

	<link href="{% static 'remote/styles.css' %}" rel="stylesheet">
	{% block stylesheets %}	{% endblock stylesheets %}
    </head>
    <body>

	<header>
	    <div class="collapse bg-dark" id="navbarHeader">
		<div class="container">
		    <div class="row">
			<div class="col-sm-8 col-md-7 py-4">
			    <h4 class="text-white">Om siden</h4>
			    <p class="text-muted">Fotobox er laget for å kunne ha speilrefleksbilder uten at noen må stå bak kameraet og være fotograf. Finn frem noen venner, still dere opp foran kameraet og gjør noe fett. Etterpå kan dere laste ned bildene direkte til telefoenen i full oppløsning. Hva venter dere på?</p>
			</div>
			<div class="col-sm-4 offset-md-1 py-4">
			    <h4 class="text-white">Kontakt</h4>
			    <ul class="list-unstyled">
				<li class="text-white">Har noe skjedd?</li>
				<li class="text-white">Kontakt {{ contact_first_name }}</li>
				<li class="text-white">{{ contact_phone_number }}</li>
			    </ul>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="navbar navbar-dark bg-dark shadow-sm">
		<div class="container d-flex justify-content-between">
		    <a href="{% url 'remote:index' %}" class="navbar-brand d-flex align-items-center">
			<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
			<strong>Fotobox</strong>
		    </a>
		    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		    </button>
		</div>
	    </div>
	</header>
	{% block content %}{% endblock content %}
	<footer class="text-muted">
	    <div class="container">
		<p class="float-right">
		    <a href="#">Tilbake til toppen</a>
		</p>
		{% block tips %}{% endblock tips %}
		<p>Vil du sette opp din egen fotobox? Eller funnet noe du ikke liker? Sjekk ut projektet på <a href="https://github.com/SimenHolmestad/Fotobox">github</a>.</p>
	    </div>
	</footer>

	<!-- Bootstrap core JavaScript
	     ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static 'remote/jquery-3.3.1.slim.min.js' %}"</script>
	<script>window.jQuery || document.write("{% static 'remote/bootstrap/popper.min.js' %}")</script>
	<script src="{% static 'remote/bootstrap/popper.min.js' %}"></script>
	<script src="{% static 'remote/bootstrap/bootstrap.min.js' %}"></script>
    </body>
</html>

remote/templates/remote/capture.html
{% extends "remote/base.html" %}
{% block content %}
    <main role="main">
	<section class="jumbotron text-center">
	    <h1 class="jumbotron-heading">Bildet ble tatt!</h1>
	    <p class="lead text-muted">Alt funket (faktisk) som det skulle. Bildet er nedenfor i full oppløsning og klar til å lagres.</p>
	    <p>
		<a href="{% url 'remote:capture' album.slug %}" class="btn btn-primary my-2">Ta nytt bilde</a>
		<a href="{% url 'remote:album' album.slug %}" class="btn btn-secondary my-2">Tilbake til album</a>
	    </p>
	</section>
    </main>
    <div class="album py-5 bg-light">
	<div class="container">
	    <div class="col-md-12">
		<div class="card mb-12 shadow-sm">
		    <img class="card-img-top" src="{{ image_link }}", alt="bilde">
		</div>
	    </div>
	</div>
    </div>
{% endblock content %}
{% block tips %}
    <p>Tips: Hvis du er på telefon, kan du holde fingeren på bildet og lagre det med menyen som kommer opp. (På iphone i hvert fall)</p>
{% endblock tips %}

remote/templates/remote/index.html
{% extends "remote/base.html" %}
{% block content %}
    <section class="jumbotron text-center">
	<div class="container">
	    <h1 class="jumbotron-heading">Hei og velkommen til Fotobox</h1>
	    <p class="lead text-muted">Du kan bruke denne siden til å ta bilder med fotoboksen eller se på bilder som allerede er tatt. Velg et album under eller lag et nytt et for å begynne! </p>
	</div>
    </section>
    <div class="album py-5 bg-light">
	<div class="container">
	    <div class="row">
		{% for album in albums %}
		    <div class="col-md-4">
			<a href="{% url 'remote:album' album.slug %}">
			    <div class="card mb-4 shadow-sm text-center">
				<h2 class="album-title">{{ album.name }}</h2>
			    </div>
			</a>
		    </div>
		{% endfor %}
		<div class="col-md-4">
		    <a href="{% url 'remote:new_album' %}">
			<div class="card mb-4 shadow-sm text-center">
			    <h2 class="album-title">Lag nytt album</h2>
			</div>
		    </a>
		</div>

	    </div>
	</div>
    </div>
{% endblock content %}

remote/templates/remote/new_album.html
{% extends "remote/base.html" %}
{% block stylesheets %}
    {% load static %}
    <link href="{% static 'remote/error.css' %}" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
    <main role="main">
	<section class="jumbotron text-center py-5">
	    <h1 class="jumbotron-heading">Lag nytt album</h1>
	    <p class="lead text-muted">Du kan kalle albumet ditt for hva som helst, for eksempel <i>vodka shots</i> eller <i>MittAlbumErKulereEnnDitt</i></p>
	</section>
	<div class ="album py-4 bg-light text-center">
	    <div class="container">
		<form method="post">{% csrf_token %}
		    {{ form.errors }}
		    {{ form.name }}
		    <br>
		    {{ form.description }}
		    <br>
		    <input type="submit" class="btn btn-primary" value="Lag album" />
		</form>
	    </div>
	</div>
    </main>
{% endblock content %}

remote/templates/remote/not_connected.html
{% extends "remote/base.html" %}
{% block stylesheets %}
    {% load static %}
    <link href="{% static 'remote/error.css' %}" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
    <main role="main">
	<section class="jumbotron text-center bg-light">
	    <h1 class="jumbotron-heading">Oooops....</h1>
	    <p class="lead text-muted">Noe gikk galt. Mulig kameraet ikke er koplet til?</p>
	    <p>
		<a href="{% url 'remote:capture' album.slug %}" class="btn btn-primary my-2">Prøv på nytt</a>
		<a href="{% url 'remote:album' album.slug %}" class="btn btn-secondary my-2">Tilbake til album</a>
	    </p>
	</section>
    </main>
{% endblock content %}

remote/templates/remote/occupied.html
{% extends "remote/base.html" %}
{% block stylesheets %}
    {% load static %}
    <link href="{% static 'remote/error.css' %}" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
    <main role="main">
	<section class="jumbotron text-center bg-light">
	    <h1 class="jumbotron-heading">Opptatt</h1>
	    <p class="lead text-muted">Kameraet er opptatt. Det er noen som bruker det akkurat nå.</p>
	    <p>
		<a href="{% url 'remote:capture' album.slug %}" class="btn btn-primary my-2">Prøv på nytt</a>
		<a href="{% url 'remote:album' album.slug %}" class="btn btn-secondary my-2">Tilbake til album</a>
	    </p>
	</section>
    </main>
{% endblock content %}

remote/templates/remote/photo.html
{% extends "remote/base.html" %}
{% block content %}
    <div class="album py-5 bg-light">
	<div class="container image-container">
	    <div class="col-md-12">
		<div class="card mb-12 shadow-sm">
		    <img class="card-img-top" src="{{ photo.image.url }}", alt="bilde">
		    <div class="card-body image-card">
			<!-- <p class="card-text">Her går det senere an å legge inn en beskrivelse av bildet??</p> -->
			<div class="d-flex justify-content-between align-items-center">
			    {% if previous_image_link %}
				<a href="{{ previous_image_link }}">
				    <button type="button" class="btn btn-sm btn-outline-secondary">Forrige bilde</button>
				</a>
			    {% endif %}
			    <small class="text-muted text-center">Bilde {{ current_photo }} av {{ photos_in_album }}<br>(highres)</small>
			    {% if next_image_link %}
				<a href="{{ next_image_link }}">
				    <button type="button" class="btn btn-sm btn-outline-secondary">Neste bilde</button>
				</a>
			    {% endif %}
			</div>
			<div class="text-center" style="padding-bottom:0">
			    <small class="time-shot-text">{{ photo.shot_time|date:'l d. F o, H:i' }}</small>
			</div>
		    </div>
		</div>
	    </div>
	</div>
	<div class="text-center" id="back-to-album">
	    <a href="{{ back_to_album_link }}" class="btn-primary btn-lg">Tilbake til album</a>
	</div>
    </div>
{% endblock content %}
{% block tips %}
    <p>Tips: Hvis du er på telefon, kan du holde fingeren på bildet og lagre det med menyen som kommer opp. (På iphone i hvert fall)</p>
{% endblock tips %}